[package]
name = "cdn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
futures = "0.3.26"

dotenv = "0.15.0"
toml = "0.5.11"

log = "0.4.17"
env_logger = "0.10.0"
ulid = "1.0.0"

lazy_static = "1.4.0"
once_cell = "1.17.0"

mongodb = "2.3.1"
rust-s3 = "0.32.3"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
validator = { version = "0.16.0", features = ["derive"] }

actix-web = "4.3.0"
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-multipart = "0.5.0"

webp = "0.2.2"
image = "0.24.5"
imagesize = "0.11.0"
ffprobe = "0.3.3"
tempfile = "3.3.0"
tree_magic_mini = "3.0.3"
content_inspector = "0.2.4"

reqwest = "0.11.14"
scraper = "0.14.0"
youtubei-rs = "1.3.5"
mime = "0.3.16"
regex = "1.7.1"
